include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    unnecessary_library_name: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    cascade_invocations: false
    use_string_in_part_of_directives: false
    always_put_required_named_parameters_first: false
    use_setters_to_change_properties: false
